### ISSUE TITLE
InverseWishart encounters a degrees-of-freedom argument error

### ISSUE THREAD

**Issue by wmkouw** [biaslab/ReactiveMP.jl#195]
I am trying to use an InverseWishart prior for the state transition covariance matrix in a linear Gaussian dynamical system:
```julia
@model function ssm(n)
    
    x = randomvar(n)
    y = datavar(Vector{Float64}, n)
    
    Q ~ InverseWishart(100, diageye(2))
    
    x_prior ~ MvNormalMeanCovariance(zeros(2), diageye(2))
    x_prev = x_prior
    
    for i in 1:n
        x[i] ~ MvNormalMeanCovariance(x_prev, Q)
        y[i] ~ MvNormalMeanCovariance(x[i], diageye(2))
        x_prev = x[i]
    end
    
    return x_prior, x, y, Q
end
```

Automatic inference, specified as below: 

```julia
constraints = @constraints begin
     q(x_prior, x,Q) = q(x_prior, x)q(Q)
end

results = inference(
    model = Model(ssm, n),
    data  = (y = y,),
    constraints = constraints,
    returnvars = (Q = KeepLast(),),
    initmarginals = (Q = vague(InverseWishart, 2),),
    initmessages = (Q = vague(InverseWishart, 2),),
)
```
leads to an ArgumentError that the degrees of freedom are too low (thrown by Distributions.jl):
```
ArgumentError: mean only defined for df > p + 1

Stacktrace:
  [1] mean
    @ ~/.julia/packages/Distributions/tFdHM/src/matrix/inversewishart.jl:87 [inlined]
  [2] macro expansion
...
```
The mean function internally converts an `ReactiveMP.InverseWishartMessage` to a `Distributions.InverseWishart` distribution, which fails when the degrees of freedom are less than or equal to the number of dimensions (here 2).

This happens for all prior degrees of freedom that I've tested. The data here is from the `Simple State Space model` demo (i.e., noisy observations of rotating 2d states).

It also seems to occur for static models, e.g. the MWE below:
```julia
@model function static(n)
    
    y = datavar(Vector{Float64}, n)
    
    Σ ~ InverseWishart(100, diageye(2))
    μ ~ MvNormalMeanCovariance(zeros(2), diageye(2))
    
    for i in 1:n
        y[i] ~ MvNormalMeanCovariance(μ, Σ)
    end
    
    return y, μ, Σ
end

constraints = @constraints begin
     q(μ,Σ) = q(μ)q(Σ)
end

results = inference(
    model = Model(static, n),
    data  = (y = y,),
    constraints = constraints,
    returnvars = (Σ = KeepLast(),),
    initmarginals = (Σ = vague(InverseWishart, 2),),
    initmessages = (Σ = vague(InverseWishart, 2),),
)
```

The `InverseWishartMessage` sent by the `MvNormalMeanCovariance` has degrees of freedom of `-d` where `d` is the dimensionality of the matrix. But that message is not converted to a `Distributions.Wishart` distribution internally. The conversion only occurs for the marginal and the marginal degrees-of-freedom calculation seems numerically stable: `df = ldf + rdf + d + 1`. So, I'm not quite sure what's causing this issue.

Versions:
- Julia: 1.7.2
- ReactiveMP: 2.4.1 (dev: master)
- GraphPPL: 2.3.1

**Comment by bvdmitri** [comment]
The bug is confirmed, the problem is in the wrongly defined `vague(InverseWishart, 2)`, which does not have the mean. The workaround is to replace `vague` in the `initmarginals` with some other value, e.g. `InverseWishart(100, diageye(2))`. @albertpod can you make a fix for that?

P.S. you do not need to `initmessages` in this example.

**Comment by wmkouw** [comment]
Ah, I was just checking the `vague` initialization. But my manual calculation of the marginal degrees-of-freedom came out to `dims+1`, which should be fine.

By the way, are you rethrowing Distributions.jl's error? Because if I just use Distributions.jl and call `p = InverseWishart(1,diageye(2))`, then I get:
```
ERROR: ArgumentError: df should be greater than dim - 1.
```

These errors are not the same: RMP tells you to pick `df > dims + 1` and Distributions says `df > dims - 1`.

**Comment by bvdmitri** [comment]
@wmkouw Both errors are from `Distributions.jl` and both are correct. One error is about Inverse-Wishart creations and another one is about its mean. So you can create an Inverse-Wishart distribution with `df <= dim`, but `mean` is not defined. You cannot create an Inverse-Wishart  with `df <= dim - 1` however, so it shows a slightly different error.

So our `vague(InverseWishart, ...)` is actually a proper distribution, but it happens to be useless, because `mean` is not defined for the chosen parameters. 

For reference:
- https://github.com/JuliaStats/Distributions.jl/blob/master/src/matrix/inversewishart.jl#L33
- https://github.com/JuliaStats/Distributions.jl/blob/master/src/matrix/inversewishart.jl#L87

**Comment by wmkouw** [comment]
Ah, I see. Thanks, this explains everything.

So what would be the proposed fix? To throw an error when the users uses a vague initialization (i.e., `df = dims`) for `initmarginals`? Or to alter vague to `df = dims+1` by default?

**Comment by bvdmitri** [comment]
I think we should alter `vague` such that it has a `mean`.
