### ISSUE TITLE
Macros @call_rule and @marginal_rule are broken for Delta node

### ISSUE THREAD

**Issue by albertpod** [biaslab/ReactiveMP.jl#210]
NOTE

**Comment by bvdmitri** [comment]
A bit of a context for the history:
Currently `ReactiveMP` cannot properly resolve a collection of messages in `@call_rule` macro for a node that can have a variable number of inputs. It happens because the collection of messages from a variable number of inputs is stored in a `Tuple`, so for rule it must be a `Tuple of Messages`. `@call_macro`, however, does not treat `Tuple`s  any differently from any other input and converts it to a `Message of Tuple` which triggers a "rule not found" error. The solution in the upcoming PR is to replace `Tuple` with an auxiliary `ManyOf` structure, for which we would have a better dispatch control.

**Comment by bvdmitri** [comment]
The fix has been merged.
