### ISSUE TITLE
Misspecified meta objects get silently ignored

### ISSUE THREAD

**Issue by MagnusKoudahl** [biaslab/ReactiveMP.jl#281]
If we consider a node that has two optional rules available dependent on the `meta` object passed, if the `meta` object is invalid the node we silently use a default `meta` instead. For example we can have a situation where `MyNode` has two available rules

```
@rule MyNode (:z,Marginalisation) (y::something, x::something, meta::Any) = begin
return 0
end

@rule MyNode (:z,Marginalisation) (y::something, x::something, meta::MyMeta) = begin
return 1
end
```
And we specify a model which includes a `meta` object. Here
```
x  ~ MyNode(y,z) where {meta=MyMeta()}
```
works correctly and returns 1 whereas
```
x  ~ MyNode(y,z) where {meta=MyMeta}
```
will returns 0 since the parentheses are missing. In the second case there is no error thrown to warn the user about incorrect specification of the `meta` object. This can lead to hard to diagnose problems since inference proceeds and yields reasonable results even though the algorithm that is executed is not the intended one.

**Comment by bvdmitri** [comment]
Small remark, I think you meant `meta::Any` and `meta::MyMeta` respectively? I don't think that `meta=Any` is a valid syntax in `@rule`. It shows me
```
ERROR: LoadError: Error in macro. Input meta = Any is incorrect
```

Note that if you don't specify `meta`, then the default meta in ReactiveMP and GraphPPL is `::Nothing` (see [here](https://github.com/biaslab/ReactiveMP.jl/blob/master/src/rule.jl#L286)), so it must have happened because you defined `Any` rule by accident? 

In any case, this is not something GraphPPL or ReactiveMP related, but Julia related. You probably defined a rule that accepts `Any` meta and `MyMeta` (without parenthesis) is `Any` from Julia point of view. So I don't know if it is possible to warn about this case. There is no indication that something has gone wrong from a language point of view.
