### ISSUE TITLE
Turing.jl benchmarks: LinearGaussianSSM

### ISSUE THREAD

**Issue by torfjelde** [biaslab/ReactiveMP.jl#64]
First I want to say: this is sick package! Nice work!

In `benchmarks/notebooks` you have a notebook benchmarking ReactiveMP.jl vs. Turing.jl on a Linear Gaussian State-Space Model.

If you make the following changes to the Turing.jl-section, you get a 30X speedup.

First off, don't make the `x` variable untyped, i.e. instead define the model as

```julia
Turing.@model function LinearGaussianSSM(y, A, B, P, Q, ::Type{TV} = Vector{Vector{Float64}}) where {TV}
    n = length(y)

    # State sequence.
    x = TV(undef, n)

    # Observe each point of the input.
    x[1] ~ MvNormal([ 0.0, 0.0 ], 1e1)
    y[1] ~ MvNormal(B * x[1], Q)

    for t in 2:n
        x[t] ~ MvNormal(A * x[t - 1], P)
        y[t] ~ MvNormal(B * x[t], Q)
    end
end;
```

Secondly, use ReverseMode.jl + Memoization.jl to use reverse-mode AD with the tape compiled, i.e. add:
```julia
using ReverseDiff, Memoization
Turing.setadbackend(:reversediff)
Turing.setrdcache(true)
```
before the sampling statements.

On my end, this brings us to 1s and 2s for the respective.

Of course, ReactiveMP.jl is much faster than is:) But I was reviewing the paper and had a look at the benchmarks, upon which I noticed that the current implementation was somewhat lacking.

And for future reference, these things are described more in detail here: https://turing.ml/dev/docs/using-turing/performancetips.

As a side-note, (from one PPL-dev to another :wink:) I'd recommend trying to ping someone from the PPLs you're comparing to when making benchmarks. This way you can ensure that you get a fair comparison :+1: Of course you have to be a bit careful in what you allow, e.g. as I Turing.jl, I could further optimize the heck out this model, _but_ I refrain from doing that as it's not really representative of what your trying to demonstrate/what a regular user would be doing. But I think the change I proposed above falls within "reasonable alterations", as we would expect performance-sensitive users to look at the docs for performance tips.

EDIT: There are also alternative samplers which would be very well-suited for this problem, e.g. Elliptical Slice Sampling (`Turing.ESS`), which would scale even better than `HMC` with reverse-mode wrt. number of data-points.

**Comment by bvdmitri** [comment]
Hey @torfjelde ! Thank you for helping us out with Turing.jl performance benchmark. It is indeed now way faster with your changes. I uploaded new benchmarks and made a pull request. You can quickly see changes here: https://app.reviewnb.com/biaslab/ReactiveMP.jl/pull/65/

Also, since we have more room now with timings I decided to increase number of points from `100` to `1000`. Performance differences (ratio) between `100` and `1000` are more or less the same (which is really cool, means Turing scales way better with new changes), but it just looks a bit better visually on the bar-plot. 

Regarding `Turing.ESS`. Scalability is more or less the same as with built-in HMC (maybe a bit better), but the posterior results are significantly worse. So I decided to keep current version. Also HMC is well known in the community, for example I have no experience with `ESS` sampler and I'm not sure I know how it works.

I also changed the documentation's introduction a bit to outline that we are aimed at conjugate state-space models.

**Comment by torfjelde** [comment]
> Thank you for helping us out with Turing.jl performance benchmark. It is indeed now way faster with your changes. I uploaded new benchmarks and made a pull request.

Great! And no worries, happy to help:)

> Also, since we have more room now with timings I decided to increase number of points from 100 to 1000. Performance differences (ratio) between 100 and 1000 are more or less the same (which is really cool, means Turing scales way better with new changes), but it just looks a bit better visually on the bar-plot.

Makes sense!:)

> Regarding Turing.ESS. Scalability is more or less the same as with built-in HMC (maybe a bit better), but the posterior results are significantly worse. So I decided to keep current version. Also HMC is well known in the community, for example I have no experience with ESS sampler and I'm not sure I know how it works.

Sure, this is also reasonable :+1:

> I also changed the documentation's introduction a bit to outline that we are aimed at conjugate state-space models.

Awesome!
